'''
our server urls are defined in this page
Created on November 7, 2013

@author: Yariv Katz
@version: 1.0
@copyright: nerdeez.com
'''

#===============================================================================
# begin imports
#===============================================================================

from django.conf.urls import patterns, include, url
from django.contrib import admin
from tastypie.api import Api
import ltg_backend_app.views
from ltg_backend_app.api.utilities import UtilitiesResource
from ltg_backend_app.api.tutor import TutorResource
from ltg_backend_app.api.user import UserResource
from ltg_backend_app.api.anonymous_user import AnonymousUserResource
from ltg_backend_app.api.user_profile import UserProfileResource
from ltg_backend_app.api.anonymous_user_profile import AnonymousUserProfileResource
from ltg_backend_app.api.question import QuestionResource
from ltg_backend_app.ltg_api.section import SectionResource
from ltg_backend_app.ltg_api.concept import ConceptResource
from ltg_backend_app.ltg_api.attempt import AttemptResource
from ltg_backend_app.ltg_api.user_concept_score import UserConceptScoreResource
from ltg_backend_app.ltg_api.user_section_score import UserSectionScoreResource
from ltg_backend_app.ltg_api.user_score import UserScoreResource
# from ltg_backend_app.ltg_api.api import *

#===============================================================================
# end imports
#===============================================================================

# enable admin
admin.autodiscover()

#register rest urls
v1_api = Api(api_name='v1')
v1_api.register(UtilitiesResource())
v1_api.register(TutorResource())
v1_api.register(UserResource())
v1_api.register(AnonymousUserResource())
v1_api.register(UserProfileResource())
v1_api.register(AnonymousUserProfileResource())
v1_api.register(QuestionResource())
v1_api.register(SectionResource())
v1_api.register(ConceptResource())
v1_api.register(AttemptResource())
v1_api.register(UserConceptScoreResource())
v1_api.register(UserSectionScoreResource())
v1_api.register(UserScoreResource())

#register urls
urlpatterns = patterns('',
    # enable admin
    url(r'^admin/', include(admin.site.urls)),
    
    #urls for tastypie
    (r'^api/', include(v1_api.urls)),
    
    #grappelli
    (r'^grappelli/', include('grappelli.urls')),
    
    ('^$', ltg_backend_app.views.homepage),
    
    # url for the api docs generated by tastypie-swagger package
    url(r'api/doc/', include('tastypie_swagger.urls', namespace='tastypie_swagger')),
    
    
)
